#! /bin/sh
#
# Set up environment variables for thames, and run it
#
ISIS_F0=/home/user/src/cpm3
ISIS_F1=/home/user/src/cpm3/plm/plm80
ISIS_F2=/home/user/src/cpm3/plm/asm80
ISIS_F3=/home/user/src/cpm3/plm/utils
export ISIS_F0 ISIS_F1 ISIS_F2 ISIS_F3

thames $*
